wut4lunch/models.py
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import UserMixin, AnonymousUserMixin
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    username = db.Column(db.String, unique=True)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)
    member_since = db.Column(db.Date)

    lunches = db.RelationshipProperty('Lunch', backref='user', lazy='dynamic')

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint
        from sqlalchemy.exc import IntegrityError
        import forgery_py

        seed()
        for x in range(count):
            name = forgery_py.name.full_name()
            email = forgery_py.internet.email_address()
            username = (name.split()[0] + str(randint(1, 500))).lower()
            password = forgery_py.lorem_ipsum.word()
            member_since = forgery_py.date.date()
            u = User(name=name, email=email, username=username, password=password, member_since=member_since)
            db.session.add(u)
            try:
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

    def __init__(self, name, username, email, password, member_since):
        self.name = name
        self.username = username
        self.email = email
        self.set_password(password)
        self.member_since = member_since

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, value):
        return check_password_hash(self.password, value)

    def is_authenticated(self):
        if isinstance(self, AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        return True

    def is_anonymous(self):
        if isinstance(self, AnonymousUserMixin):
            return True
        else:
            return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User %r>' % self.username


class Lunch(db.Model):
    __tablename__ = 'lunches'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(128))
    pub_date = db.Column(db.DateTime)
    visible_to = db.Column(db.String(12))
    enjoyed = db.Column(db.String())

    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint, choice
        from sqlalchemy.exc import IntegrityError
        import forgery_py

        seed()
        user_count = User.query.count()
        enjoyed = choice(['delicious', 'tasty', 'nice', 'ok', 'nasty'])
        for x in range(count):
            u = User.query.offset(randint(0, user_count - 1)).first()
            l = Lunch(text=forgery_py.lorem_ipsum.word(), pub_date=forgery_py.date.date(), visible_to='all', enjoyed=enjoyed, author_id=u.id)
            db.session.add(l)
            try:
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

    def __init__(self, text, pub_date, visible_to, enjoyed, author_id):
        self.text = text
        self.pub_date = pub_date
        self.visible_to = visible_to
        self.enjoyed = enjoyed
        self.author_id = author_id

    def __repr__(self):
        return '<Lunch %r>' % self.lunch

wut4lunch/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, SubmitField, ValidationError, BooleanField, SelectField
from wtforms.validators import InputRequired, Email, Length, EqualTo
from flask.ext.login import current_user
from wut4lunch.models import User


class LoginForm(Form):
    email = StringField('Email Address', validators=[InputRequired('You must enter your email.'), Email()])
    password = PasswordField('Password', validators=[InputRequired('You must enter your password.')])
    submit = SubmitField('Login')


class RegisterForm(Form):
    name = StringField('My name is:', validators=[InputRequired('You must enter your name.')])
    email = StringField('My email is:', validators=[InputRequired('You must enter your email.'), Email()])
    password = PasswordField('My top secret password is:', validators=[InputRequired('You must enter a password.'),
                                                                       Length(8, 20,
                                                                              'Your password must be 8 - 20 characters.'),
                                                                       EqualTo('confirm', 'Passwords must match.')])
    confirm = PasswordField('Confirm your password:', validators=[InputRequired('You must confirm your password.')])
    submit = SubmitField('Sign up')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email has already been registered.')


class ChangePassword(Form):
    old_password = PasswordField('What is your old password?', validators=[InputRequired('You must enter your old password.')])
    new_password = PasswordField('What is your new password?', validators=[InputRequired('You must enter a new password.'),
                                                                       Length(8, 20,
                                                                              'Your password must be 8 - 20 characters.'),
                                                                       EqualTo('confirm', ' New passwords must match.')])
    confirm = PasswordField('Confirm your new password.', validators=[InputRequired('You must confirm your new password.')])
    submit = SubmitField('Change password')

    def validate_password(self, field):
        user = User.query.filter_by(id=current_user.id).first()
        if not user.check_password(field.data):
            raise ValidationError('Old password is not correct.')


class AddLunch(Form):
    lunch = StringField('For lunch, I had:',
                        validators=[InputRequired('You\'ve got to enter what you ate - that\'s the point!')])
    enjoyed = SelectField('I found my lunch:',
                          choices=[('delicious', 'Really delicious'), ('tasty', 'Quite tasty'), ('nice', 'Nice enough'),
                                   ('ok', 'Okay, I guess'), ('nasty', 'Pretty nasty')])
    visible_to = SelectField('My lunch is visible to:',
                             choices=[('all', 'Everyone'), ('followers', 'My followers'), ('me', 'Just me')])
    submit = SubmitField('Share lunch!')

wut4lunch/__init__.py
#! ../env/bin/python
import os

from flask import Flask
from webassets.loaders import PythonLoader as PythonAssetsLoader

from wut4lunch import assets
from wut4lunch.models import db

from wut4lunch.extensions import (
    cache,
    assets_env,
    debug_toolbar,
    login_manager,
)


def create_app(object_name, env="prod"):
    app = Flask(__name__)

    app.config.from_object(object_name)
    app.config['ENV'] = env

    #init the cache
    cache.init_app(app)

    debug_toolbar.init_app(app)

    #init SQLAlchemy
    db.init_app(app)

    login_manager.init_app(app)

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().iteritems():
        assets_env.register(name, bundle)

    # register our blueprints
    from controllers.main import main
    app.register_blueprint(main)

    return app

if __name__ == '__main__':
    # Import the config for the proper environment using the
    # shell var APPNAME_ENV
    env = os.environ.get('APPNAME_ENV', 'prod')
    app = create_app('wut4lunch.settings.%sConfig' % env.capitalize(), env=env)

    app.run()

wut4lunch/controllers/main.py
import datetime

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask.ext.login import logout_user, login_required, current_user, login_user

from wut4lunch import cache
from wut4lunch.forms import LoginForm, AddLunch, RegisterForm, ChangePassword
from wut4lunch.models import db, User, Lunch

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = AddLunch()
    page = request.args.get('page', 1, type=int)
    pagination = Lunch.query.filter_by(visible_to='all').order_by(Lunch.pub_date.desc()).paginate(page, 12)
    lunches = pagination.items
    if form.validate_on_submit():
        lunch = Lunch(text=form.lunch.data, pub_date=datetime.datetime.now(), enjoyed=form.enjoyed.data, visible_to=form.visible_to.data, author_id=current_user.id)
        db.session.add(lunch)
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('index.html', form=form, lunches=lunches)


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/profile/<username>')
@login_required
def profile(username):
    form = AddLunch()
    user = User.query.filter_by(username=username).first()
    if user:
        lunches = Lunch.query.filter_by(author_id=user.id).all()
        return render_template('profile.html', user=user, form=form, lunches=lunches)
    else:
        return render_template('errors/404.html', form=form), 404


@main.route('/profile/<username>/change-password', methods=['GET', 'POST'])
@login_required
def change_password(username):
    form = AddLunch()
    password_form = ChangePassword()
    user = User.query.filter_by(username=username).first()
    if user:
        if user.username == current_user.username:
            if password_form.validate_on_submit():
                user.password = user.set_password(password_form.new_password.data)
                db.session.add(user)
                db.session.commit()
                flash('Password changed successfully!', 'success')
                return redirect(url_for(change_password, username=current_user.username))
            for error in password_form.errors.items():
                flash(error[1][0], 'danger')
            return render_template('auth/change_password.html', form=form, password_form=password_form)
        else:
            return render_template('errors/401.html', form=form), 401
    else:
        return render_template('errors/404.html', form=form), 404


@main.route('/lunch/<lunch_id>')
def lunch(lunch_id):
    form = AddLunch()
    lunch = Lunch.query.filter_by(id=lunch_id).first()
    if lunch:
        if lunch.visible_to == 'all':
            return render_template('lunches/lunch.html', lunch=lunch, form=form)
        elif lunch.visible_to != 'all' and lunch.author_id == current_user.id:
            return render_template('lunches/lunch.html', lunch=lunch, form=form)
        else:
            return render_template('lunches/private_lunch.html', form=form)
    else:
        return render_template('errors/404.html', form=form), 404


@main.route('/signin', methods=['GET', 'POST'])
def signin():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            return redirect(request.args.get('next') or url_for('.index'))
        flash('Invalid email or password.', 'danger')
    for error in form.errors.items():
        flash(error[1][0], 'danger')
    return render_template('auth/signin.html', form=form)


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.email.data.replace('.', '').split('@')[0]
        user = User(name=form.name.data, email=form.email.data, username=username, password=form.password.data,
                    member_since=datetime.datetime.now())
        db.session.add(user)
        db.session.commit()
        flash('You can now sign in!', 'success')
        return redirect(url_for('.signin'))
    for error in form.errors.items():
        flash(error[1][0], 'danger')
    return render_template('auth/signup.html', form=form)


@main.route('/signout')
def signout():
    logout_user()
    flash('You have been successfully signed out.', 'success')
    return redirect(url_for('.signin'))

wut4lunch/templates/about.html
{% extends 'layout.html' %}

{% block title %}About{{ super() }}{% endblock %}

{% block content %}
    <h1>About Wut 4 Lunch</h1>
    <hr/>
    <h3>What is it?</h3>
{% endblock %}

wut4lunch/templates/index.html
{% extends 'layout.html' %}

{% block title %}All Lunches{{ super() }}{% endblock %}

{% block content %}
{#    <div class="jumbotron">#}
        <h1>Salivate over all the lunches!</h1>
        {% if lunches %}
            <p>These are all the lunches that everyone across Wut 4 Lunch is sharing! Currently, {{ lunches|length }} lunches have been shared.</p>
                <div class="row">
                    {% for lunch in lunches %}
                        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                            <div class="tile">
                                <h2 class="tile-title">{{ lunch.text|title }}</h2>
                                <p>Shared by {{ lunch.user.name }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
        {% else %}
            <p>Looks like no one has posted any lunch yet! Why not be the first?</p>
        {% endif %}
{#    </div>#}
{% endblock %}

wut4lunch/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#2C3E50">
    <title>{% block title %} - Wut 4 Lunch{% endblock %}</title>
    {% assets 'common_css' %}<link rel="stylesheet" href="{{ ASSET_URL }}"/>{% endassets %}
</head>
<body>
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target="#main_nav" type="button">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% if current_user.is_authenticated() %}
                    <a class="navbar-brand" href="{{ url_for('main.index') }}">Wut 4 Lunch</a>
                {% else %}
                    <a class="navbar-brand" href="#">Wut 4 Lunch</a>
                {% endif %}
            </div>
            <div class="collapse navbar-collapse" id="main_nav">
                {% if current_user.is_authenticated() %}
                    <ul class="nav navbar-nav">
                        <li><a href="#" data-toggle="modal" data-target="#addModal">Add <span class="glyphicon glyphicon-plus"></span></a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Lunches<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('main.index') }}">All Lunches</a></li>
                                <li><a href="#">Friend's Lunches</a></li>
                                <li><a href="#">Your Lunches</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ current_user.name }}<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('main.profile', username=current_user.username) }}">View Profile</a></li>
                                <li><a href="{{ url_for('main.change_password', username=current_user.username) }}">Change Password</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('main.signout') }}">Sign Out</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('main.about') }}">About</a></li>
                        <li><a href="{{ url_for('main.signin') }}">Sign In</a></li>
                        <li><a href="{{ url_for('main.signup') }}">Sign Up</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% if current_user.is_authenticated() %}
            <div class="modal fade" id="addModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title">Share your lunch!</h4>
                        </div>
                        <div class="modal-body">
                            <form method="POST">
                                {{ form.csrf_token }}
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ form.lunch.label }}
                                        {{ form.lunch(class='form-control', placeholder='Braised cabbage', required='required') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ form.enjoyed.label }}
                                        {{ form.enjoyed(class='form-control') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ form.visible_to.label }}
                                        {{ form.visible_to(class='form-control') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ form.submit(class='btn btn-primary btn-lg form-control add-button') }}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
{% assets 'common_js' %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
</html>

wut4lunch/templates/profile.html
{% extends 'layout.html' %}

{% block title %}
    {% if current_user.username == user.username %}
        Your Profile{{ super() }}
    {% else %}
        {{ user.username }}'s Profile{{ super() }}
    {% endif %}
{% endblock %}

{% block content %}
{#    <div class="jumbotron">#}
        {% if current_user.username == user.username %}
            <h1>Hello, {{ current_user.name }}!</h1>
            <hr/>
            <p>You have been a member since {{ current_user.member_since.strftime('%d %B %Y') }}. Your lunches include:</p>
            <ul>
            {% for lunch in lunches %}
                <li>{{ lunch.text }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <h1>{{ user.username }}'s Profile</h1>
            <hr/>
            <div class="row">
                <div class="col-md-3">
                    <div class="tile">
                        <h3 class="tile-title">Lunches</h3>
                        <ul>
                            {% for lunch in lunches %}
                                <li>{{ lunch.text }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="tile">
                        <h3 class="tile-title">Name</h3>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="tile">
                        <h3 class="tile-title">Name</h3>
                    </div>
                </div>
            </div>
        {% endif %}
{#    </div>#}
{% endblock %}